# Generated by Django 5.0.4 on 2024-04-29 09:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="descrption",
            new_name="description",
        ),
    ]
